config/routes.rb
PluginRegistry::Application.routes.draw do
  resources :plugins
  resources :authors
  match 'search' => "search#index"

  root :to => "plugins#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :plugins

  def self.current
    self.new
  end

  def can_edit?(plugin)
    true
  end

  def to_s
    self.name
  end
end

app/models/plugin.rb
class Plugin < ActiveRecord::Base
  belongs_to :author

  validates_presence_of :author, :identifier, :name

  has_friendly_id :identifier
  validates_uniqueness_of :identifier
  # the same as ChiliProject
  validates_format_of :identifier, :with => /^(?!\d+$)[a-z0-9\-_]*$/, :if => Proc.new { |p| p.identifier_changed? }

  has_one :screenshot
  has_many :screenshots

  def short_description
    # TODO: render this properly...
    first_line = description.split("\n\n").first
  end
end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  has_attached_file :image, :styles => ({
    :thumb => "120x88>",
    :medium => "180x133>",
    :large => "640x480>"
  })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def show
    respond_with @author
  end

protected
  def find_author
    @author = Author.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  respond_to :html, :xml, :json
  respond_to :atom, :only => :index

  before_filter :find_plugin, :only => [:show, :edit, :update, :destroy]
  before_filter :authorize, :only => [:edit, :update, :destroy]

  ORDER_BY = {
    'name' => 'name',
    'updated' => 'updated_at DESC'
  }

  def index
    if params[:format] != "atom"
      order = ORDER_BY[params[:order_by]] || ORDER_BY['name']
    else
      order = ORDER_BY['updated']
    end

    @plugins = Plugin.order(order).page(params[:page]).includes(:author, :screenshot)
    respond_with @plugins
  end

  def show
    respond_with @plugin
  end

  def new
    @plugin = Plugin.new
    respond_with @plugin
  end

  def create
    @plugin = Plugin.new(params[:plugin])
    flash[:notice] = t(:plugin_registered) if @plugin.save
    respond_with @plugin
  end

  def edit
    respond_with @plugin
  end

  def update
    @plugin.update_attributes(params[:plugin])
    flash[:notice] = t(:plugin_updated) if @plugin.save
    respond_with @plugin
  end

  def destroy
    flash[:notice] = t(:plugin_destroyed) if @plugin.destroy
    respond_with @plugin
  end

protected
  def find_plugin
    @plugin = Plugin.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize
    unless Author.current.can_edit?(@plugin)
      respond_with({:error => "You can only edit your own plugins"}, :status => :forbidden)
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_author(author, *args)
    link_to(author, author, *args)
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/plugins_helper.rb
module PluginsHelper
  def view_orders(current)
    PluginsController::ORDER_BY.keys.sort.collect do |order|
      if current == order
        t ".order_by_#{order}"
      else
        link_to t(".order_by_#{order}"), :order => order
      end
    end.join(' | ')
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= @title
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
  %body{:class => controller.controller_name}
    %header
      #logo
        .title ChiliProject
        .subtitle Plugin Registry
        .parent_site= link_to "ChiliProject.org", "http://www.chiliproject.org"
      %nav
        .account_links
          Welcome back
        %ul.primary_links
          %li#index_link{:class => ("here" if @selected == :home)}
            = link_to "Home", root_path
          %li#index_link{:class => ("here" if @selected == :plugins)}
            = link_to "Plugins", plugins_path
          %li#authors_link{:class => ("here" if @selected == :authors)}
            = link_to "Authors", authors_path
          %li#search_link{:class => ("here" if @selected == :search)}
            = link_to "Search", search_path
    - if content_for? :head
      #head
        = yield :header
    %content
      - flash.keys.each do |key|
        %p{:id=>key}= flash[key]
      - if content_for? :actions
        #actions
          = yield :actions
      - unless (@h1 || @title).blank?
        %h1= @h1 || h(@title)
      = yield

    - if content_for? :sidebar
      %sidebar
        = yield :sidebar

  %footer
    %p
      The <a href="https://github.com/chiliproject/plugin-registry">source code</a>
      for this website is available on GitHub. Contact us on the
      <a href="https://www.chiliproject.org/projects/chiliproject/boards">ChiliProject Forums</a>
      if you are interested in contributing, or just send us a pull request.
      Please direct bug reports, feature requests, and comments to the <a href="https://www.chiliproject.org/projects/chiliproject/issues">issue tracker</a>.

app/views/plugins/_plugin.html.haml
section.plugin
  - unless defined?(hide_screenshot) && hide_screenshot
    - if plugin.screenshot
      .screenshot= image_tag plugin.screenshot.url(:thumb), :width=>120, :alt => "Screenshot of #{plugin.name}"
    -else
      .screenshot= image_tag "missing_thumb.png", :alt => t(:no_screenshot)

  .info
    .name
      = link_to plugin.name, plugin
      - unless defined?(hide_edit) && hide_edit
        = link_to "Edit", edit_plugin_path(plugin), :class=>"action" if Author.current.can_edit?(plugin)
        .description= plugin.short_description
      - unless defined? hide_author && hide_author
        .authored
          by
          = link_to_author plugin.author

app/views/plugins/index.html.haml
- @title = "ChiliProject Plugins"
- @h1 = "Plugins"
- @selected = :plugins

- content_for :actions do
  = link_to( "Add Plugin", new_plugin_path, :class => "button-plus")

.view_order
  View
  != view_orders(@order)

= paginate @plugins

= render :partial => "plugin", :collection => @plugins

= paginate @plugins

app/views/plugins/show.html.haml
- @title = @plugin.name
- @title << " plugin" unless @title.match(/plugin/)
- @title << " - ChiliProject"
- h1 = h(@plugin.name)
- h1 << " #{link_to "Edit", edit_plugin_path(@plugin), :class => 'action'}".html_safe if Author.current.can_edit?(@plugin)
- @h1 = h1.html_safe
- @selected = :plugins

.screenshot
  - if @plugin.screenshot
    = link_to image_tag(@plugin.screenshot.url(:medium)), @plugin.screenshot.url(:large)
  - else
    = image_tag "missing_medium.png", :alt => t(:no_screenshot)

%div{:style=>"width: 75%"}

  .big
    = @plugin.description.to_s

  %table.attributes
    %tr
      %th Author
      %td= link_to_author @plugin.author
    - if @plugin.homepage.present?
      %tr
        %th Website
        %td= link_to h(@plugin.homepage), @plugin.homepage
    - if @plugin.repository_url.present?
      %tr
        %th Repository
        %td= link_to h(@plugin.repository_url), @plugin.repository_url
    - if @plugin.download_url.present?
      %tr
        %th Download
        %td= link_to h(@plugin.download_url), @plugin.download_url
    %tr
      %th Record Created
      %td
        = @plugin.created_at.to_date.to_s(:long)
        = "(#{time_ago_in_words(@plugin.created_at)} ago)"
    - if @plugin.updated_at > @plugin.created_at + 1.day
      %tr
        %th Last Updated
        %td
          = @plugin.updated_at.to_date.to_s(:long)
          = "(#{time_ago_in_words(@plugin.updated_at)} ago)"

  .installation
    %h3 Installation
    %p
      At the command prompt, in the root of your ChiliProject installation, type:
      %pre
        %code
          = "script/chili_plugin install #{@plugin.identifier}"
    = @plugin.installation_instructions

  - if false #can_edit?(@plugin)
    %p
      = link_to(image_tag("trash.png", :class => "icon") + " Delete", plugin_path(@plugin), :method => :delete, :confirm => "Are you sure you want to delete this plugin?", :class => "button")

- if @plugin.screenshot
  .screenshot-zoom
    = image_tag(@plugin.screenshot.url(:large))
    = link_to "close", "#"